spring:
  application:
    name: Eureka Server
server:
  port: ${SERVER_PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8000}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    response-cache-update-interval-ms: 5000
  instance:
    prefer-ip-address: true